version: "3.8"
services:
  blog:
    build: .
    volumes:
      - .:/var/www/html
    container_name: blog

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - blog
